# Builds and pushes Docker images on:
# - Weekly schedule (Monday 2 AM UTC) for security updates
# - Version tags (v1.0.0, etc.) for releases
# - Manual workflow dispatch
name: Build and Push Docker Image

on:
  schedule:                       # Weekly builds on Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  push:
    tags: [ 'v*' ]                # Only on version tags (releases)
  workflow_dispatch:              # Manual trigger button in GitHub UI
    inputs:
      tag:
        description: 'Custom tag for the build'
        required: false
        default: 'manual'

env:
  REGISTRY: docker.io
  IMAGE_NAME: awushensky/nut-client

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy  # Add this line to use the deploy environment
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=${{ github.event.inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' }}
          type=schedule,pattern={{date 'YYYYMMDD'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
